# This is a basic workflow to help you get started with Actions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: self-hosted
    steps:
       - name: Linux
         run: |
           rm -rf ./beefrontend.AppImage
           git clone --recurse-submodule https://github.com/frc5183/beefrontend/
           cp ./beefrontend/buildtools/love.AppImage ./love.AppImage
           chmod +x ./love.AppImage
           ./love.AppImage --appimage-extract
           zip -9 -r ./beefrontend.love ./beefrontend/src/
           cat squashfs-root/bin/love beefrontend.love > squashfs-root/bin/beefrontend
           chmod +x squashfs-root/bin/beefrontend
           wget "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"
           chmod a+x appimagetool-x86_64.AppImage
           sed 's/(?:^|\W)Exec=love %f(?:$|\W)/\nExec=beefrontend %f\n/g' ./squashfs-root/love.desktop
           ./appimagetool-x86_64.AppImage squashfs-root ./beefrontend.AppImage
           rm -rf ./love.AppImage
           rm -rf ./beefrontend
           rm -rf ./appimagetool-x86_64.AppImage
           rm -rf ./squashfs-root
           rm -rf ./beefrontend.love
       - name: Artifact AppImage
         uses: actions/upload-artifact@v3
         with:
            name: beefrontend.AppImage
            path: beefrontend.AppImage
